BASE=mecanica-uis-2014
n=-03
NAME=${BASE}${n}

all:
	pdflatex ${NAME}.tex
	pdflatex ${NAME}.tex

clean:
	rm -f *.aux *.lof *.log *.lot *.out *.toc *.nlo *.bbl *.blg *.brf *.ilg *.ind *.nls *.bak *.synctex.gz
